### ISSUE TITLE
Add brand `Kelvinator`. Make it easier to add other brands

### ISSUE THREAD

**Issue by willemolding** [redgridone/redgrid-cli#6]

**Comment by simwilso** [comment]
hey @willemolding I tried adding my Kelvinator AC on friday but had no luck.  Not sure if my process was correct so had a few questions on the process for my testing:

1) The Kelvinator brand is not in there so I didn't use the command:
`# find supported remote indices for your IR device and AC brand
redgrid ac-remotes --deviceId xxx --brand Samsung`

2) so I skipped and went straight to this step:
`redgrid add-remote --deviceId xxx --remoteIndex ##Code##`

3) then once the virtual remote was added I tried this step:
`redgrid command-ac --deviceId xxx --remoteId yyy --remoteIndex ##Code## --command '{"power": 1, "temp": 25}'`

**QUESTION:**
I tried using remote code from [this URL](https://removeandreplace.com/2016/06/17/universal-air-conditioner-remote-control-codes/). Is this correct or do you think I should be using another set of codes (six digits?)?

**QUESTION2:**
do I need to add a virtual remote for each of the remote code options above (see my step 2) then try step three entering the command for the same remoteIndex?
In my testing I only tried the first 'remoteIndex' (remote code) in the list for Kelvinator in the URL.

**QUESTION3:**
is there a command to clean up virtual remotes that don't work.
i.e.. is there a command syntax for deleting a remoteId?

**Comment by simwilso** [comment]
air conditioner added, tested and working in latest branch and AC fix.
